apiVersion: apps/v1
kind: Deployment
metadata:
  name: bharath-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bharath-app
  template:
    metadata:
      labels:
        app: bharath-app
    spec:
      containers:
      - name: bharath-app
        image: <your-dockerhub-username>/bharath-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bharath-app-service
spec:
  type: NodePort
  selector:
    app: bharath-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
